Upgrade to Neutrino 9 RC
This also required upgrading Jest to version 24 since I was getting this error:

> TypeError: Cannot read property 'cwd' of undefined